// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/accounts": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get all bank accounts of the logged-in user",
                "produces": ["application/json"],
                "tags": ["accounts"],
                "summary": "List user accounts",
                "parameters": [
                    {"type": "integer", "description": "Page number", "name": "page", "in": "query"},
                    {"type": "integer", "description": "Items per page", "name": "limit", "in": "query"}
                ],
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/api/v1/accounts/balances": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get balances of all accounts of the logged-in user",
                "produces": ["application/json"],
                "tags": ["accounts"],
                "summary": "List all account balances",
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/api/v1/accounts/{accountId}/balance": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get balance of a specific account",
                "produces": ["application/json"],
                "tags": ["accounts"],
                "summary": "Get account balance",
                "parameters": [
                    {"type": "string", "description": "Account ID", "name": "accountId", "in": "path", "required": true}
                ],
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"},
                    "404": {"description": "Not Found"}
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate user with email and password",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["auth"],
                "summary": "User login",
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/api/v1/beneficiaries": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get beneficiary list of the logged-in user",
                "produces": ["application/json"],
                "tags": ["beneficiaries"],
                "summary": "List beneficiaries",
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/api/v1/transfer-modes": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Get available transfer modes",
                "produces": ["application/json"],
                "tags": ["transfer-modes"],
                "summary": "List transfer modes",
                "responses": {
                    "200": {"description": "OK"},
                    "401": {"description": "Unauthorized"}
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Bank Server API",
	Description:      "Production-grade banking backend service API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
